#!/bin/bash

unset CDPATH
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

set -e
set -x

targetdir="$1"

[ -n "$targetdir" ] || {
    echo "usage: build <outputdir>" >&2
    exit 64
}

pushd "$targetdir"

wget -c http://cloud-images.ubuntu.com/releases/13.10/release/ubuntu-13.10-server-cloudimg-amd64-disk1.img
wget -c http://cloud-images.ubuntu.com/releases/13.10/release/ubuntu-13.10-server-cloudimg-amd64.ovf

popd

source "$DIR"/ansible/hacking/env-setup
