#!/bin/bash

unset CDPATH
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

set -e

unset cleanup_kernels
unset cleanup_aptcache
unset cleanup_mountpoint_aptcache
unset cleanup_mountpoint_proc
unset cleanup_mountpoint
unset cleanup_partition1
unset cleanup_lodev
unset cleanup_bad_ova
unset cleanup_dest_img
unset cleanup_ovf
unset cleanup_original_image
unset cleanup_created_image
unset cleanup_mf
cleanup() {
    [ -n "$NOCLEANUP" -a "$1" != "force" ] && exit || true
    [ -z "$cleanup_kernels" ] || {
        rm -rf "$cleanup_kernels"
        unset cleanup_kernels
    }
    [ -z "$cleanup_mountpoint_aptcache" ] || {
        umount "$cleanup_mountpoint_aptcache"
        unset cleanup_mountpoint_aptcache
    }
    [ -z "$cleanup_aptcache" ] || {
        rm -rf "$cleanup_aptcache"
        unset cleanup_aptcache
    }
    [ -z "$cleanup_mountpoint_proc" ] || {
        umount "$cleanup_mountpoint_proc"
        unset cleanup_mountpoint_proc
    }
    [ -z "$cleanup_mountpoint" ] || {
        umount "$cleanup_mountpoint"
        unset cleanup_mountpoint
    }
    [ -z "$cleanup_partition1" ] || {
        rmdir "$cleanup_partition1"
        unset cleanup_partition1
    }
    [ -z "$cleanup_lodev" ] || {
        losetup -d "$cleanup_lodev"
        unset cleanup_lodev
    }
    [ -z "$cleanup_bad_ova" ] || {
        rm -f "$cleanup_bad_ova"
        unset cleanup_bad_ova
    }
    [ -z "$cleanup_dest_img" ] || {
        rm -f "$cleanup_dest_img"
        unset cleanup_dest_img
    }
    [ -z "$cleanup_ovf" ] || {
        rm -f "$cleanup_ovf"
        unset cleanup_ovf
    }
    [ -z "$cleanup_original_image" ] || {
        rm -f "$cleanup_original_image"
        unset cleanup_original_image
    }
    [ -z "$cleanup_created_image" ] || {
        rm -f "$cleanup_created_image"
        unset cleanup_created_image
    }
    [ -z "$cleanup_mf" ] || {
        rm -f "$cleanup_mf"
        unset cleanup_mf
    }
}
trap cleanup EXIT

chkdsk() {
    retval=0 ; e2fsck -f "$lodev"p1 || retval=$?
    if [ "$retval" == "0" -o "$retval" == "1" -o "$retval" == "2" -o "$retval" == "3" ] ; then
        return 0
    else
        return "$retval"
    fi
    return 0
}

targetdir="$1"

[ -n "$targetdir" ] || {
    echo "usage: build <outputdir>" >&2
    exit 64
}

pushd "$targetdir" > /dev/null

#download
if [ ! -f ubuntu-13.10-server-cloudimg-amd64-disk1.raw ] ; then
    wget -c --progress=bar https://cloud-images.ubuntu.com/releases/13.10/release/ubuntu-13.10-server-cloudimg-amd64-disk1.img
fi

#conversion to raw
if [ ! -f ubuntu-13.10-server-cloudimg-amd64-disk1.raw ] ; then
    qemu-img convert -O raw ubuntu-13.10-server-cloudimg-amd64-disk1.img ubuntu-13.10-server-cloudimg-amd64-disk1.raw
fi

#growth of the file (64 GB)
size=$((64*1024*1024*1024))
lastsector=$(($size/512-1))
if [ `stat -c%s ubuntu-13.10-server-cloudimg-amd64-disk1.raw` != $size ] ; then
    python -c '
import sys
f = open(sys.argv[1], "ab")
maxsize = long(sys.argv[2])
f.truncate(maxsize)
f.close()
' ubuntu-13.10-server-cloudimg-amd64-disk1.raw $size
fi

#growth of the enclosing partition
if echo p | fdisk ubuntu-13.10-server-cloudimg-amd64-disk1.raw | grep -q $lastsector ; then
    true
else
    echo '
d
n
p



w
' | fdisk ubuntu-13.10-server-cloudimg-amd64-disk1.raw
fi

#mapping to loopback dev
lodev=`
losetup -l | python -c '
import sys
stuffs = dict([ (l[41:-1],l[0:10]) for l in sys.stdin.readlines()[1:] ])
if sys.argv[1] in stuffs:
    print stuffs[sys.argv[1]]
' "$PWD"/ubuntu-13.10-server-cloudimg-amd64-disk1.raw
`
if [ -z "$lodev" ] ; then
    lodev=`losetup -P --find --show "$PWD"/ubuntu-13.10-server-cloudimg-amd64-disk1.raw`
fi
cleanup_lodev="$lodev"

#resize partitions
if ! mountpoint -q partition1 ; then
        # do NOT do this if the file system is mounted
        chkdsk "$lodev"p1
        resize2fs "$lodev"p1
fi

#mount partitions
mkdir -p partition1
cleanup_partition1="$PWD"/partition1
mountpoint -q partition1 || mount "$lodev"p1 partition1
cleanup_mountpoint="$PWD"/partition1
mountpoint -q partition1/proc || mount -t proc proc partition1/proc
cleanup_mountpoint_proc="$PWD"/partition1/proc

#create apt cache directory
mkdir -p "$PWD"/aptcache
cleanup_aptcache="$PWD"/aptcache
mountpoint -q "$cleanup_mountpoint"/var/cache/apt/archives || mount --bind "$cleanup_aptcache" "$cleanup_mountpoint"/var/cache/apt/archives
cleanup_mountpoint_aptcache="$cleanup_mountpoint"/var/cache/apt/archives

popd > /dev/null

#setup networking in chroot
mv -f "$cleanup_mountpoint"/etc/resolv.conf "$cleanup_mountpoint"/etc/resolv.conf.original
cp -f /etc/resolv.conf "$cleanup_mountpoint"/etc/resolv.conf

#fool system into believing that shit exists
fakedir="$cleanup_mountpoint"/fake
mkdir -p "$fakedir"
for a in update-grub initctl invoke-rc.d restart start stop start-stop-daemon service ; do
    echo "#/bin/bash" | tee "$fakedir"/$a > /dev/null
    chmod +x "$fakedir"/$a
done

#fire ansible up
ANSIBLE_NOCOWS=1 PATH=/fake:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin ansible-playbook -c chroot -i "$cleanup_mountpoint", "$DIR"/setup.yml

#restore networking in chroot
cp -Rf "$cleanup_mountpoint"/etc/resolv.conf.original "$cleanup_mountpoint"/etc/resolv.conf

#cleanup the fake stuff
rm -rf "$fakedir"

#reduce size of image
rm -rf "$cleanup_mountpoint"/var/lib/apt/lists/*
rm -rf "$cleanup_mountpoint"/var/cache/apt/pkgcache*
rm -rf "$cleanup_mountpoint"/var/cache/apt/srcpkgcache*

#get the kernel and initrd out
mkdir -p "$targetdir"/kernels
cleanup_kernels="$targetdir"/kernels
for a in "$cleanup_mountpoint"/boot/vmlinuz-* ; do
    kernel=`basename "$a"`
    cp -fR "$a" "$cleanup_kernels"
    break
done
for a in "$cleanup_mountpoint"/boot/initrd.img-* ; do
    initrd=`basename "$a"`
    cp -fR "$a" "$cleanup_kernels"
    break
done

#write creation of bootloader
cat > "$cleanup_mountpoint"/installbootloader << EOF
#!/bin/bash
set -x
mount / -o remount,rw
grub-install /dev/sda
update-initramfs -c -t -k all
update-grub
rm -f /installbootloader
sync
echo 1 > /proc/sys/kernel/sysrq
echo u > /proc/sysrq-trigger
sync
echo o > /proc/sysrq-trigger
sleep 1
echo cannot power off VM.  Please kill -15 this qemu process.
EOF
chmod +x "$cleanup_mountpoint"/installbootloader

#cleanup everything but the lodev
savedshit="$cleanup_lodev"
savedshit2="$cleanup_kernels"
savedshit3="$cleanup_aptcache"
unset cleanup_lodev
unset cleanup_kernels
unset cleanup_aptcache
cleanup force
cleanup_lodev="$savedshit"
cleanup_kernels="$savedshit2"
cleanup_aptcache="$savedshit3"
unset savedshit
unset savedshit2
unset savedshit3

#install bootloader
vmuuid=`python -c 'import uuid; print str(uuid.uuid1())'`
qemu-system-x86_64 -enable-kvm -name dts-publishingstudio -M pc-1.2 -no-reboot -m 512 -uuid "$vmuuid" -kernel "$cleanup_kernels"/"$kernel" -initrd "$cleanup_kernels"/"$initrd" -append "root=/dev/sda1 ro quiet init=/installbootloader console=ttyS0" -drive file="$lodev",if=none,id=drive-ide0-0-0,format=raw -device ide-hd,bus=ide.0,unit=0,drive=drive-ide0-0-0,id=ide0-0-0,bootindex=1 -nographic -serial /dev/stdout
chkdsk "$lodev"p1

if [ -z "$NOZEROFREE" ] ; then
    #zerofree the partition image
    zerofree -v "$lodev"p1
fi

#copy the OVF
cp -f "$DIR"/dts-publishingstudio-13.10-amd64.ovf "$targetdir"
cleanup_ovf="$targetdir"/dts-publishingstudio-13.10-amd64.ovf

pushd "$targetdir" > /dev/null

#create image
cleanup_dest_img="$PWD"/dts-publishingstudio-13.10-amd64-disk1.vmdk
# because the next command fails unless I do this
rm -f dts-publishingstudio-13.10-amd64-disk1.vmdk
# because of suggestion in https://github.com/ceph/inktank-training-vms/commit/52bc4084e39739e4778a694153b5f8309cdb0b82#diff-a53108f7543b75adbb34afc035d4cdf6R29
vboxmanage convertfromraw --format=VMDK --variant=Stream ubuntu-13.10-server-cloudimg-amd64-disk1.raw dts-publishingstudio-13.10-amd64-disk1.vmdk
chmod 644 dts-publishingstudio-13.10-amd64-disk1.vmdk

ovfsum=`sha1sum dts-publishingstudio-13.10-amd64.ovf | cut -d ' ' -f 1`
imgsum=`sha1sum dts-publishingstudio-13.10-amd64-disk1.vmdk | cut -d ' ' -f 1`

#generate manifest for extra anti-tampering goodness
cleanup_mf="$PWD"/dts-publishingstudio-13.10-amd64.mf
cat > dts-publishingstudio-13.10-amd64.mf << EOF
SHA1 (dts-publishingstudio-13.10-amd64.ovf)= $ovfsum
SHA1 (dts-publishingstudio-13.10-amd64-disk1.vmdk)= $imgsum
EOF

#tar it all up
cleanup_bad_ova="$PWD"/dts-publishingstudio-13.10-amd64.ova
tar cv dts-publishingstudio-13.10-amd64.ovf dts-publishingstudio-13.10-amd64-disk1.vmdk dts-publishingstudio-13.10-amd64.mf > dts-publishingstudio-13.10-amd64.ova
cleanup_bad_ova=

cleanup_original_image="$targetdir"/ubuntu-13.10-server-cloudimg-amd64-disk1.vmdk
cleanup_created_image="$targetdir"/ubuntu-13.10-server-cloudimg-amd64-disk1.raw

popd > /dev/null
