---
- hosts: all
  tasks:
    - name: set hostname
      copy: content=publishingstudio.declinefm.com dest=/etc/hostname
    - name: install necessary packages
      apt: pkg=ubuntu-desktop,audacity,git,sox,vlc,lame,libid3-tools
    - name: remove undesirable packages
      apt: pkg=totem,rhythmbox state=absent
# the initial password is simply 'password', lowercase
    - name: create group ubuntu
      group: name=ubuntu
    - name: create user ubuntu
      user: name=ubuntu group=ubuntu groups=admin update_password=on_create password=$1$SomeSalt$/jbIwfYCu0MxPBND2EtRH.
    - name: clone studio repository
      git: repo=https://github.com/Rudd-O/studio dest=/usr/local/studio
    - name: wire repository up into path
      copy: src=files/studio.sh dest=/etc/profile.d/studio.sh
    - name: create swap files
      shell: creates=/var/swap dd if=/dev/zero of=/var/swap bs=1M count=0 seek=2048 && chmod 700 /var/swap && mkswap /var/swap
    - name: add swap file to fstab
      lineinfile: dest=/etc/fstab regexp=^/var/swap line='/var/swap none swap defaults 0 0'
