---
- hosts: all
  tasks:
    - name: set hostname
      copy: content=publishingstudio.declinefm.com dest=/etc/hostname
    - name: add hostname to hosts file
      lineinfile: dest=/etc/hosts regexp=publishingstudio.declinefm.com line='127.0.0.2 publishingstudio.declinefm.com publishingstudio'
    - name: speed up APT downloads
      lineinfile: dest=/etc/apt/sources.list line='deb http://us-west-1.ec2.archive.ubuntu.com/ubuntu/ {{ item }} main restricted universe multiverse' insertbefore=BOF regexp='http://us-west-1.ec2.archive.ubuntu.com/ubuntu/ {{ item }}'
      with_items:
        - "{{ ansible_distribution_release }}"
        - "{{ ansible_distribution_release }}-updates"
        - "{{ ansible_distribution_release }}-security"
    - name: add latest ansible PPA
      apt_repository: repo='ppa:rquillo/ansible'
    - name: install necessary packages
      apt: update_cache=yes pkg=linux-image-extra-virtual,dkms,ubuntu-desktop,ansible
    - name: install audio priority file
      copy: src=files/audio.conf dest=/etc/security/limits.d/audio.conf
    - name: install audio suite
      apt: pkg=audacity,git,sox,vlc,lame,libid3-tools,sonic-visualiser,paman,jackd2,qjackctl,pulseaudio-module-jack
    - name: install jack control starter
      copy: src=files/jackcontrol.desktop dest=/etc/xdg/autostart/jackcontrol.desktop
    - name: install virtualbox packages
      apt: pkg=virtualbox-guest-x11,virtualbox-guest-utils,virtualbox-guest-dkms
    - name: create {{ item }} link for virtualbox-guest-x11
      file: state=link src=/etc/init.d/virtualbox-guest-x11 dest=/etc/{{ item }}/S21virtualbox-guest-x11
      with_items:
        - rc2.d
        - rc3.d
        - rc4.d
        - rc5.d
    - name: remove undesirable packages
      apt: pkg=totem,rhythmbox,openssh-server,cloud-init state=absent purge=yes
    - name: create swap files
      shell: creates=/var/swap dd if=/dev/zero of=/var/swap bs=1M count=2048 && chmod 700 /var/swap && mkswap /var/swap
    - name: add swap file to fstab
      lineinfile: dest=/etc/fstab regexp=^/var/swap line='/var/swap none swap defaults 0 0'
# the initial password is simply 'password', lowercase
    - name: create group ubuntu
      group: name=ubuntu
    - name: create user ubuntu
      user: name=ubuntu comment='Show publisher' group=ubuntu groups=admin,audio shell=/bin/bash update_password=on_create password='$6$xBdsWlF/$G9zAtal56nQ9LO8kMnIsZNe223djh7./9Nu5MSd34qZAuwBAycfD/wlCP4G9jYW/y9yuuNEs3CV5yH5EvQVG31'
    - name: create dts-publishingstudio
      file: state=directory dest=/usr/local/dts-publishingstudio
    - name: create dts-publishingstudio/utils
      file: state=directory dest=/usr/local/dts-publishingstudio/utils
    - name: copy utils there
      copy: mode=0755 src={{ item }} dest=/usr/local/dts-publishingstudio/utils/
      with_fileglob:
      - utils/*
    - name: wire utils directory into path
      file: state=link src=/usr/local/dts-publishingstudio/utils/studio.sh dest=/etc/profile.d/studio.sh
    - name: create {{ item }} directory
      file: owner=ubuntu group=ubuntu dest=/home/ubuntu/{{ item }} state=directory mode=0755
      with_items:
        - Studio
        - Studio/Recordings
        - Studio/Clips
        - .config
        - .config/rncbc.org
        - .config/jack
        - .audacity-data
        - .audacity-data/Chains
    - name: install jack config
      copy: owner=ubuntu group=ubuntu src=files/conf.xml dest=/home/ubuntu/.config/jack/conf.xml
    - name: set up audacity config
      lineinfile: create=yes owner=ubuntu group=ubuntu state=present
                  dest=/home/ubuntu/.audacity-data/audacity.cfg
                  insertafter={{ item.insertafter }}
                  regexp='{{ item.regexp }}'
                  line='{{ item.line }}'
      with_items:
      - { insertafter: '',        regexp: '.AudioIO.', line: '[AudioIO]' }
      - { insertafter: 'AudioIO', regexp: '^RecordingDevice', line: 'RecordingDevice=system' }
      - { insertafter: 'AudioIO', regexp: '^PlaybackDevice', line: 'PlaybackDevice=system' }
      - { insertafter: 'AudioIO', regexp: '^Host', line: 'Host=JACK Audio Connection Kit' }
    - name: copy chains to audacity chains dir
      copy: mode=0644 owner=ubuntu group=ubuntu
            src={{ item }} dest=/home/ubuntu/.audacity-data/Chains/
      with_fileglob:
      - files/Chains/*
    - name: set up qjackctl config
      ini_file: owner=ubuntu group=ubuntu dest=/home/ubuntu/.config/rncbc.org/QJackCtl.conf
                section={{ item.section }} option={{ item.option }} value={{ item.value }}
      with_items:
      - { section: 'Settings', option: 'Server', value: '/usr/bin/jackd' }
      - { section: 'Settings', option: 'Realtime', value: 'true' }
      - { section: 'Settings', option: 'NoMemLock', value: 'false' }
      - { section: 'Settings', option: 'Frames', value: '1024' }
      - { section: 'Settings', option: 'Periods', value: '2' }
      - { section: 'Settings', option: 'SampleRate', value: '48000' }
      - { section: 'Settings', option: 'Driver', value: 'alsa' }
      - { section: 'Settings', option: 'Audio', value: '2' }
      - { section: 'Options', option: 'DBusEnabled', value: 'true' }
    - name: add {{ item }} local directory to Nautilus bookmarks
      lineinfile: owner=ubuntu group=ubuntu dest=/home/ubuntu/.gtk-bookmarks regexp='Local {{ item }}' line='file:///home/ubuntu/Studio/{{ item }} Local {{ item }}' create=yes
      with_items:
        - Recordings
        - Clips
    - name: add {{ item }} remote directory to Nautilus bookmarks
      lineinfile: owner=ubuntu group=ubuntu dest=/home/ubuntu/.gtk-bookmarks regexp='Server {{ item }}' line='sftp://ubuntu@studio.declinefm.com/home/ubuntu/Studio/{{ item }} Server {{ item }}' create=yes
      with_items:
        - Recordings
        - Clips
    - name: create .ssh directory
      file: owner=ubuntu group=ubuntu dest=/home/ubuntu/.ssh state=directory mode=0700
    - name: add studio to known_hosts
      lineinfile: owner=ubuntu group=ubuntu dest=/home/ubuntu/.ssh/known_hosts create=yes mode=0600 regexp='studio.declinefm.com' line='studio.declinefm.com,184.73.165.116 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDoDZ789FU010XtTmqzn0E6aQUKH+gyykkLnoRUDn/l+oZY4T/S+ns7kuMzYiJvaMfyPCyQ5Jz57BAVXpoI/NQS/G6sNowMg+P3/i/QLRrm06pJK9hTjc1fiALtmcYn7FLCdM285s811Go0WA7gTW/Vn+ZgDSe5bEbnjQot4AfPSH2DTT5pYDsKhwIFi2CSjgI66c8prOdyrsy9a0j2zDyJ7NTj7JQ4EEisxEaKCE1L49VXVbIrcBBPpPqR9c8BzxgzPlR6uruZTqCG0lqFVEeN/3TqvpfNB/XmUiDC4cSrKIAASmb40Hiloo1TwFsjh4M7K655QmOCGeRYUzfJiX5r'
    - name: reset desktop settings and unity launcher icons
      shell: sudo -H -u ubuntu /usr/local/dts-publishingstudio/utils/reset-desktop-settings
      register: reset_launcher_icons
      changed_when: reset_launcher_icons.stdout.find("configuration changed") != -1
    - name: empty apt lists
      shell: rm -rf /var/lib/apt/lists/*
    - name: clear apt cache (except for files)
      shell: rm -rf /var/cache/apt/pkgcache* /var/cache/apt/srcpkgcache*
    - name: enable autologin
      copy: src=files/90-autologin.conf dest=/etc/lightdm/lightdm.conf.d/90-autologin.conf
    - name: remove wrong boot options
      file: state=absent dest=/etc/default/grub.d/50-cloudimg-settings.cfg
    - name: set right boot options
      copy: src=files/50-studio-settings.cfg dest=/etc/default/grub.d/50-studio-settings.cfg
