#!/bin/bash

set -e

unset CDPATH
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

[ -n "$STUDIOARCHIVEDIR" ]   || { echo '$STUDIOARCHIVEDIR is not defined, exiting' ; exit 40 ; }

for a in "$STUDIOARCHIVEDIR"/Recordings/*.ogg ; do
    test -f "$a" || continue
    test -f "$a.wav" && continue || true
    "$DIR"/decodeoggtofloatwav "$a" "$a.wav" &
done

wait
