#!/bin/bash -e

[ -n "$STUDIOARCHIVEDIR" ]   || { echo '$STUDIOARCHIVEDIR is not defined, exiting' ; exit 40 ; }
mkdir -p "$STUDIOARCHIVEDIR"

host=`head -1 ~/.studiohosts` || {
   echo '$0: could not determine studio host.  have you launched the studio yet?' 1>&2
   exit 5
}

rsync -a --progress "$host":Studio/Recordings/ "$STUDIOARCHIVEDIR"/Recordings/
