#!/usr/bin/env python

from gi.repository import Gtk

builder = Gtk.Builder()
builder.add_from_file("../ui/uploadshows.ui")
builder.connect_signals({"onDestroy": Gtk.main_quit})

window = builder.get_object("window")
window.show_all()

Gtk.main()
